apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Values.managed_by }}
type: Opaque
stringData:
  .stormforger.toml: |-
    jwt = {{ .Values.auth.token | quote }}
